from enum import IntEnum


class FaceProcessingStatus(IntEnum):
    UNKNOWN_ERROR = 0
    SUCCESS = 1
    UNEXPECTED_ERROR = 2
    SOURCE_IMAGE_NO_FACE_ERROR = 3
    TARGET_IMAGE_NO_FACE_ERROR = 4
    IMAGE_NO_FACE_ERROR = 5
    TARGET_IMAGE_FACE_INDEX_OUT_OF_RANGE_ERROR = 6
    TARGET_IMAGE_FACE_INDEX_NAN_ERROR = 7,
    NO_REQUIRED_ARGS_ERROR = 8,
    EMPTY_ARG_ERROR = 9,
    BAD_IMAGE_ERROR = 10,
